export const KOTA_ID: { [province: string]: string[] } = {
  Aceh: ['Banda Aceh', 'Langsa', 'Lhokseumawe', 'Sabang', 'Subulussalam'],
  Bali: ['Denpasar', 'Singaraja', 'Tabanan'],
  'Bangka Belitung': ['Pangkal Pinang', 'Tanjung Pandan'],
  Banten: ['Cilegon', 'Serang', 'Tangerang', 'Tangerang Selatan'],
  Bengkulu: ['Bengkulu', 'Curup'],
  Gorontalo: ['Gorontalo'],
  Jambi: ['Jambi', 'Muarabungo', 'Sarolangun', 'Sungai Penuh'],
  'Jawa Barat': ['Bandung', 'Bekasi', 'Bogor', 'Cimahi', 'Depok', 'Sukabumi', 'Tasikmalaya'],
  'Jawa Tengah': ['Magelang', 'Pekalongan', 'Salatiga', 'Semarang', 'Surakarta', 'Tegal'],
  'Jawa Timur': [
    'Batu',
    'Blitar',
    'Kediri',
    'Madiun',
    'Malang',
    'Mojokerto',
    'Pasuruan',
    'Probolinggo',
    'Surabaya',
  ],
  'Kalimantan Barat': ['Pontianak', 'Singkawang'],
  'Kalimantan Selatan': ['Banjarbaru', 'Banjarmasin'],
  'Kalimantan Tengah': ['Palangka Raya'],
  'Kalimantan Timur': ['Balikpapan', 'Bontang', 'Samarinda', 'Tarakan'],
  'Kalimantan Utara': ['Tanjung Selor'],
  'Kepulauan Riau': ['Batam', 'Tanjung Pinang'],
  Lampung: ['Bandar Lampung', 'Kotabumi', 'Metro'],
  Maluku: ['Ambon', 'Tual'],
  'Maluku Utara': ['Ternate', 'Tidore'],
  'Nusa Tenggara Barat': ['Bima', 'Mataram'],
  'Nusa Tenggara Timur': ['Kupang', 'Sumbawa Besar'],
  Papua: ['Jayapura'],
  'Papua Barat': ['Manokwari', 'Sorong'],
  Riau: ['Dumai', 'Pekanbaru'],
  'Sulawesi Barat': ['Mamuju'],
  'Sulawesi Selatan': ['Makassar', 'Palopo', 'Parepare'],
  'Sulawesi Tengah': ['Palu'],
  'Sulawesi Tenggara': ['Baubau', 'Kendari'],
  'Sulawesi Utara': ['Bitung', 'Kotamobagu', 'Manado', 'Tomohon'],
  'Sumatera Barat': ['Bukittinggi', 'Padang', 'Padang Panjang', 'Pariaman', 'Sawahlunto', 'Solok'],
  'Sumatera Selatan': ['Lubuklinggau', 'Pagar Alam', 'Palembang', 'Prabumulih'],
  'Sumatera Utara': [
    'Binjai',
    'Medan',
    'Padangsidimpuan',
    'Pematangsiantar',
    'Sibolga',
    'Tanjungbalai',
    'Tebing Tinggi',
  ],
  Yogyakarta: ['Bantul', 'Gunung Kidul', 'Kulon Progo', 'Sleman', 'Yogyakarta'],
};
