export const DATA_PENYAKIT: Record<string, string> = {
  P01: "FLU DAN BATUK (ISPA)",
  P02: "TYPHUS (TYPHOID FEVER)",
  P03: "DIARE (GASTROENTERITIS)",
  P04: "MAAG (GASTRITIS)",
  P05: "TEKANAN DARAH TINGGI (HIPERTENSI)",
  P06: "TEKANAN DARAH RENDAH (HIPOTENSI)",
  P07: "KENCING MANIS (DIABETES MELITUS)",
  P08: "REMATIK (ARTHRITIS)",
  P09: "RADANG TENGGOROKAN (FARINGITIS)",
  P010: "DEMAM BERDARAH (DENGUE HEMORRAGIC)",
};

export const DATA_GEJALA: Record<string, string> = {
  G01: "Demam",
  G02: "Nyeri Tenggorokan",
  G03: "Hidung tersumbat",
  G04: "Sakit kepala",
  G05: "Bersin-bersin",
  G06: "Hidung Berair",
  G07: "Pusing",
  G08: "Kelelahan",
  G09: "Nyeri otot dan sendi",
  G010: "Sakit perut",
  G011: "Kehilangan nafsu makan",
  G012: "Ruam kulit",
  G013: "Intensitas BAB meningkat",
  G014: "Konsistensi tinja cair",
  G015: "Perut kram",
  G016: "Mual dan muntah",
  G017: "Dehidrasi",
  G018: "Perut kembung",
  G019: "Sering bersendawa",
  G020: "Gangguan pencernaan",
  G021: "Nyeri dada",
  G022: "Susah nafas",
  G023: "Penglihatan kabur",
  G024: "Mudah emosi",
  G025: "Mudah gelisah",
  G026: "Lemas",
  G027: "Pernapasan cepat",
  G028: "Kulit pucat",
  G029: "Denyut jantung meningkat",
  G030: "Penurunan berat badan",
  G031: "Luka sulit sembuh",
  G032: "Rasa haus berlebih",
  G033: "Sering BAK",
  G034: "Infeksi berulang",
  G035: "Kaku pagi hari",
  G036: "Lemah otot",
  G037: "Suara serak",
  G038: "Nyeri saat menelan",
  G039: "Nyeri telinga",
  G040: "Pendarahan ringan",
};
